data:
  path: "data/raw/dataset.csv"
  test_size: 0.2
  random_seed: 42

preprocessing:
  normalize: True
  normalization_method: "minmax"
  feature_selection:
    method: "PCA"
    n_components: 10

model:
  type: "RandomForest"
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42
training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  validation_split: 0.2

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
